server:
  port: 8081

restClient:
  accountUrl: http://gateway-server-service/api/account

eureka:
  client:
    service:
      url:
        defaultZone: http://localhost:8096/eureka
  instance:
    preferIpAddress: true
    
spring:
  data:
    mongodb:
      uri: mongodb+srv://leonel:leonel@cluster0.we5wo.mongodb.net/bank

