spring:
  data:
    mongodb:
      uri: mongodb+srv://leonel:leonel@cluster0.we5wo.mongodb.net/bank




restClient:
  accountUrl: test
  creditUrl: test
  transactionUrl: test
  
      
#restClient:
#  accountUrl: http://gateway-server-service/api/account
#  creditUrl: http://gateway-server-service/api/credit
#  transactionUrl: http://gateway-server-service/api/transaction

eureka:
  client:
    service-url:
        defaultZone: https://bootcamp-nttdata-eureka-server.azurewebsites.net/eureka
  instance:
    preferIpAddress: true



